import type * as Types from "src/types";
export const levels = [
  { value: "A1", label: "A1" },
  { value: "A2", label: "A2" },
  { value: "B1", label: "B1" },
  { value: "B2", label: "B2" },
  { value: "C1", label: "C1" },
  { value: "C2", label: "C2" },
];

export const sortOptions = [
  { value: "relevance", label: "Liên quan nhất" },
  { value: "popular", label: "Phổ biến nhất" },
  { value: "newest", label: "Mới nhất" },
];

export const tagOptions: Types.Tag[] = [
  { _id: "1", name: "Ngữ pháp", type: "skill", color: "#f59e42" },
  { _id: "2", name: "Nói", type: "skill", color: "#38bdf8" },
  { _id: "3", name: "Từ vựng", type: "skill", color: "#34d399" },
  { _id: "4", name: "Nghe", type: "skill", color: "#a78bfa" },
  { _id: "5", name: "Đọc", type: "skill", color: "#f87171" },
  { _id: "6", name: "Viết", type: "skill", color: "#fbbf24" },
  { _id: "7", name: "Phát âm", type: "skill", color: "#10b981" },
  { _id: "8", name: "Giao tiếp", type: "skill", color: "#3b82f6" },
  { _id: "9", name: "Kiểm tra", type: "topic", color: "#8b5cf6" },
  { _id: "10", name: "Giải trí", type: "topic", color: "#ec4899" },
];

export const courses: Types.Course[] = [
  {
    _id: "1",
    title: "Tiếng Anh giao tiếp A1",
    tags: ["1", "8"],
    thumbnail: "",
    description: "Khóa học tiếng Anh giao tiếp cho người mới bắt đầu.",
    level: "A1",
    lessons: [],
    rewardCoins: 100,
    rewardItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    title: "Tiếng Anh giao tiếp A2",
    tags: ["1", "8"],
    thumbnail: "",
    description: "Khóa học tiếng Anh giao tiếp cho người mới bắt đầu.",
    level: "A2",
    lessons: [],
    rewardCoins: 100,
    rewardItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    title: "Tiếng Anh giao tiếp B1",
    tags: ["1", "8"],
    thumbnail: "",
    description: "Khóa học tiếng Anh giao tiếp cho người mới bắt đầu.",
    level: "B1",
    lessons: [],
    rewardCoins: 100,
    rewardItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    title: "Tiếng Anh giao tiếp B2",
    tags: ["1", "8"],
    thumbnail: "",
    description: "Khóa học tiếng Anh giao tiếp cho người mới bắt đầu.",
    level: "B2",
    lessons: [],
    rewardCoins: 100,
    rewardItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    title: "Tiếng Anh giao tiếp C1",
    tags: ["1", "8"],
    thumbnail: "",
    description: "Khóa học tiếng Anh giao tiếp cho người mới bắt đầu.",
    level: "C1",
    lessons: [],
    rewardCoins: 100,
    rewardItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    title: "Tiếng Anh giao tiếp C2",
    tags: ["1", "8"],
    thumbnail: "",
    description: "Khóa học tiếng Anh giao tiếp cho người mới bắt đầu.",
    level: "C2",
    lessons: [],
    rewardCoins: 100,
    rewardItems: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];